import type { Analysis } from '../analyze.ts';
import { conceptClass } from '../registry/types.ts';
import { graph } from './graph.ts';

// MAP.md — the high-altitude entry point that defeats grab-bag: every concept,
// grouped by class, with its constituent files (by @partOf), a kind breakdown,
// and its @uses consumers. Fully sorted, so it is byte-stable in CI and a diff
// means a real structural change.
export const generate = (a: Analysis): string => {
  const g = graph(a);

  const fileKinds: Record<string, string[]> = {};
  for (const { path, annotation } of a.files) if (annotation) fileKinds[path] = annotation.kind;

  const byClass: Record<string, string[]> = {};
  for (const concept of Object.keys(a.config.concepts)) {
    const cls = conceptClass(concept) ?? 'other';
    (byClass[cls] ??= []).push(concept);
  }

  const lines: string[] = ['# MAP', '', '_Generated by `atlas generate`. Do not edit by hand._', ''];

  for (const cls of Object.keys(byClass).sort()) {
    lines.push(`## ${cls}`, '');
    for (const concept of byClass[cls]!.sort()) {
      lines.push(`### ${concept}`);

      const entry = a.config.concepts[concept]!;
      for (const field of Object.keys(entry).sort()) {
        const values = entry[field];
        if (values?.length) lines.push(`- ${field}: ${values.join(', ')}`);
      }

      const members = g.conceptToFiles[concept] ?? [];
      const counts: Record<string, number> = {};
      for (const file of members) for (const k of fileKinds[file] ?? []) counts[k] = (counts[k] ?? 0) + 1;
      const breakdown = Object.keys(counts)
        .sort()
        .map((k) => `${k}(${counts[k]})`)
        .join(', ');
      lines.push(`- files (${members.length})${breakdown ? `: ${breakdown}` : ''}`);
      for (const file of members) lines.push(`  - ${file} — ${(fileKinds[file] ?? []).join(', ')}`);

      const consumers = g.usesConsumers[concept] ?? [];
      if (consumers.length) {
        lines.push(`- consumers (${consumers.length}):`);
        for (const file of consumers) lines.push(`  - ${file}`);
      }
      lines.push('');
    }
  }

  return `${lines.join('\n').trimEnd()}\n`;
};
