import type { ConceptGraph, CoverageReport, Gaps } from '../commands/report.ts';

// Injective sanitizer for Mermaid node ids: distinct concept ids never collide
// (encoding the char code keeps `feature:billing` and `feature.billing` apart).
export const safeId = (id: string): string =>
  id.replace(/[^a-zA-Z0-9]/g, (c) => `_${c.charCodeAt(0)}_`);

// Escape a Mermaid quoted-label so a `"` in a concept id can't break the diagram
// or inject directives.
const safeLabel = (s: string): string => s.replace(/"/g, '&quot;');

const totalsTable = (t: Gaps): string =>
  [
    '| metric | count |',
    '|--------|------:|',
    `| files | ${t.files} |`,
    `| missing block | ${t.missingBlock} |`,
    `| missing @kind (required) | ${t.missingKind} |`,
    `| missing @partOf (required) | ${t.missingPartOf} |`,
    `| @uses uncurated | ${t.usesUncurated} |`,
    `| @uses curated-empty | ${t.usesCuratedEmpty} |`,
    `| @uses curated | ${t.usesCurated} |`,
    `| @uses proposed | ${t.usesProposed} |`,
  ].join('\n');

const pie = (t: Gaps): string =>
  [
    '```mermaid',
    'pie title Annotation coverage',
    `  "annotated" : ${t.files - t.missingBlock}`,
    `  "missing block" : ${t.missingBlock}`,
    '```',
  ].join('\n');

const categoryTable = (report: CoverageReport): string => {
  const head = [
    '| category | files | no block | no @kind | no @partOf | uncurated | curated-empty | curated |',
    '|----------|------:|---------:|---------:|-----------:|----------:|--------------:|--------:|',
  ];
  const rows = report.categories.map(
    (c) =>
      `| ${c.category} | ${c.files} | ${c.missingBlock} | ${c.missingKind} | ${c.missingPartOf} | ${c.usesUncurated} | ${c.usesCuratedEmpty} | ${c.usesCurated} |`,
  );
  return [...head, ...rows].join('\n');
};

const conceptGraph = (graph: ConceptGraph): string => {
  const lines = ['```mermaid', 'graph LR'];
  const byClass: Record<string, typeof graph.nodes> = {};
  for (const n of graph.nodes) {
    const bucket = byClass[n.cls] ?? [];
    byClass[n.cls] = bucket;
    bucket.push(n);
  }
  for (const cls of Object.keys(byClass).sort()) {
    lines.push(`  subgraph ${cls}`);
    for (const n of byClass[cls]!) lines.push(`    ${safeId(n.id)}["${safeLabel(n.id)}"]`);
    lines.push('  end');
  }
  for (const e of graph.edges) lines.push(`  ${safeId(e.source)} --> ${safeId(e.target)}`);
  lines.push('```');
  return lines.join('\n');
};

// COVERAGE.md — diffable, GitHub-native (Mermaid renders inline). Totals + a
// coverage pie + a per-category gap table + the concept dependency graph.
export const renderCoverageMarkdown = (report: CoverageReport, graph: ConceptGraph): string =>
  [
    '# Coverage',
    '',
    '_Generated by `atlas report`. Do not edit by hand._',
    '',
    '## Totals',
    '',
    totalsTable(report.total),
    '',
    pie(report.total),
    '',
    '## By category',
    '',
    'Grouped by effective concept (declared `@partOf`, else the rules’ predicted concept). `@uses` columns',
    'are curation signals, not failures.',
    ...(report.filesInMultipleConcepts > 0
      ? [
          '',
          `> ${report.filesInMultipleConcepts} file(s) belong to multiple concepts, so the per-category file counts sum to more than the total.`,
        ]
      : []),
    '',
    categoryTable(report),
    '',
    '## Concept graph',
    '',
    'Edges are `@partOf` → `@uses`: a concept depends on what its files use.',
    '',
    conceptGraph(graph),
    '',
  ].join('\n');
