import type { CoverageReport, Gaps, SeamGraph } from '../commands/report.ts';

const safeId = (id: string): string => id.replace(/[^a-zA-Z0-9]/g, '_');

const totalsTable = (t: Gaps): string =>
  [
    '| metric | count |',
    '|--------|------:|',
    `| files | ${t.files} |`,
    `| missing block | ${t.missingBlock} |`,
    `| missing @kind (required) | ${t.missingKind} |`,
    `| missing @partOf (required) | ${t.missingPartOf} |`,
    `| @uses uncurated | ${t.usesUncurated} |`,
    `| @uses curated-empty | ${t.usesCuratedEmpty} |`,
    `| @uses curated | ${t.usesCurated} |`,
    `| @uses proposed | ${t.usesProposed} |`,
  ].join('\n');

const pie = (t: Gaps): string =>
  ['```mermaid', 'pie title Annotation coverage', `  "annotated" : ${t.files - t.missingBlock}`, `  "missing block" : ${t.missingBlock}`, '```'].join(
    '\n',
  );

const categoryTable = (report: CoverageReport): string => {
  const head = [
    '| category | files | no block | no @kind | no @partOf | uncurated | curated-empty | curated |',
    '|----------|------:|---------:|---------:|-----------:|----------:|--------------:|--------:|',
  ];
  const rows = report.categories.map(
    (c) =>
      `| ${c.category} | ${c.files} | ${c.missingBlock} | ${c.missingKind} | ${c.missingPartOf} | ${c.usesUncurated} | ${c.usesCuratedEmpty} | ${c.usesCurated} |`,
  );
  return [...head, ...rows].join('\n');
};

const seamGraph = (graph: SeamGraph): string => {
  const lines = ['```mermaid', 'graph LR'];
  const byClass: Record<string, typeof graph.nodes> = {};
  for (const n of graph.nodes) (byClass[n.cls] ??= []).push(n);
  for (const cls of Object.keys(byClass).sort()) {
    lines.push(`  subgraph ${cls}`);
    for (const n of byClass[cls]!) lines.push(`    ${safeId(n.id)}["${n.id}"]`);
    lines.push('  end');
  }
  for (const e of graph.edges) lines.push(`  ${safeId(e.source)} --> ${safeId(e.target)}`);
  lines.push('```');
  return lines.join('\n');
};

// COVERAGE.md — diffable, GitHub-native (Mermaid renders inline). Totals + a
// coverage pie + a per-category gap table + the seam dependency graph.
export const renderCoverageMarkdown = (report: CoverageReport, graph: SeamGraph): string =>
  [
    '# Coverage',
    '',
    '_Generated by `atlas report`. Do not edit by hand._',
    '',
    '## Totals',
    '',
    totalsTable(report.total),
    '',
    pie(report.total),
    '',
    '## By category',
    '',
    'Grouped by effective seam (declared `@partOf`, else the rules’ predicted seam). `@uses` columns',
    'are curation signals, not failures.',
    '',
    categoryTable(report),
    '',
    '## Seam graph',
    '',
    'Edges are `@partOf` → `@uses`: a seam depends on what its files use.',
    '',
    seamGraph(graph),
    '',
  ].join('\n');
